# Generated by Django 5.2.8 on 2025-11-09 11:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=20, verbose_name='Номер машины')),
                ('owner', models.CharField(max_length=100, verbose_name='Владелец')),
                ('previous_owners', models.TextField(blank=True, null=True, verbose_name='Прошлые владельцы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание машины')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
            ],
        ),
        migrations.CreateModel(
            name='CarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='add_car/', verbose_name='Фотография')),
                ('is_number_plate', models.BooleanField(default=False, verbose_name='На фото с номерным знаком')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='add_car.car')),
            ],
        ),
    ]
