# Generated by Django 5.2.8 on 2025-11-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
    ]
