# Generated by Django 5.2.8 on 2025-11-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_car', '0002_car_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание машины'),
        ),
        migrations.AlterField(
            model_name='car',
            name='previous_owners',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Прошлые владельцы'),
        ),
    ]
